
services:
  mongodb:
    image: mongo:7
    container_name: vedaai-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: vedaai_assessment_creator
    volumes:
      - mongodb_data:/data/db
  

  redis:
    image: redis:7
    container_name: vedaai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: